// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MailComposetestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mailComposetest() {
    driver.get("https://mailcomposepage.w3spaces.com/saved-from-Tryit-2024-09-11-aspwn.html");
    driver.manage().window().setSize(new Dimension(1060, 816));
    driver.findElement(By.id("to")).click();
    driver.findElement(By.id("to")).sendKeys("Irushisilva1234@gmail.com");
    driver.findElement(By.id("subject")).click();
    driver.findElement(By.id("subject")).sendKeys("regarding buying a new laptop");
    driver.findElement(By.id("body")).click();
    driver.findElement(By.id("body")).sendKeys("pls send me your price list");
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("body")).click();
    driver.findElement(By.id("body")).sendKeys("send me the price list");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Email sent successfully!"));
  }
}
